### ISSUE TITLE
error running the notebook in conda

### ISSUE THREAD

**Issue by asmakaus** [fepegar/miccai-educational-challenge-2019#3]
%%capture
tf2pt.checkpoint_tf_to_state_dict_tf(

    input_checkpoint_tf_path=input_checkpoint_tf_path,

    output_csv_tf_path=output_csv_tf_path,

    output_state_dict_tf_path=output_state_dict_tf_path,

    filter_out_function=highresnet_mapping.is_not_valid,

    replace_string='HighRes3DNet/',

)

data_frame_tf = pd.read_csv(output_csv_tf_path)

state_dict_tf = torch.load(output_state_dict_tf_path)

Process Process-1:
Traceback (most recent call last):
  File "/home/asma/anaconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/asma/anaconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/asma/My_Projects_Cardio/miccai-educational-challenge-2019/tf2pt.py", line 126, in checkpoint_tf_to_state_dict_tf_
    save_relative_paths=False, filename=None)
  File "/home/asma/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 813, in __init__
    "When eager execution is enabled, `var_list` must specify a list "
RuntimeError: When eager execution is enabled, `var_list` must specify a list or dict of variables to save

**Comment by asmakaus** [comment]
The issue was resolved by using older version of tensorflow with python 3.6 and disabling my gpu with conda 10.
